# Nvidia environment variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = WLR_NO_HARDWARE_CURSORS,1
env = NVD_BACKEND,direct

# Gaming/Proton optimizations
env = PROTON_ENABLE_NVAPI,1
env = PROTON_HIDE_NVIDIA_GPU,0
env = DXVK_ASYNC,1

# Extra env variables
# env = MY_GLOBAL_ENV,setting
