-- Entry point; load order matters. noctalia.lua is runtime-generated — until it
-- exists Hyprland falls back to hyprland.conf (self-heals once Noctalia runs).
-- On NixOS, hyprland.conf and nixos.lua (scroll-overview, desktop only) are
-- generated by nixos-config; hyprland.lua beats hyprland.conf.

require("env")
require("monitor")
require("config")
require("noctalia")
require("workspaces")
require("rule")
require("bind")
require("autostart")
pcall(require, "nixos")
