-- Hyprland entry point
-- Mirrors mango/config.conf's `source =` structure.
-- Load order matters: env → monitor → config → noctalia → workspaces →
-- rule → bind → autostart.
-- See ~/.config/mango/config.conf and ~/.config/niri/config.kdl for sibling configs.
--
-- noctalia.lua is runtime-generated by Noctalia (theme colors), not part of
-- this repo. On a machine where Noctalia has never run, the require fails
-- and Hyprland falls back to hyprland.conf — by design; it self-heals after
-- noctalia.service first writes the file.
--
-- NOTE: NixOS deploys a patched copy of this tree (nixos-config
-- home/dotfiles.nix) and appends the scroll-overview plugin block to this
-- file. Hyprland prefers hyprland.lua over hyprland.conf when both exist.

require("env")
require("monitor")
require("config")
require("noctalia")
require("workspaces")
require("rule")
require("bind")
require("autostart")
