-- Entry point; load order matters. noctalia.lua (colours) is written by Noctalia at
-- runtime and loaded optionally, so a missing file can't take every bind down with it.
-- On NixOS, hyprland.conf and nixos.lua (scroll-overview, desktop only) are
-- generated by nixos-config; hyprland.lua beats hyprland.conf.

require("env")
require("monitor")
require("config")
-- Noctalia's apply.sh looks for the text require("noctalia") and appends one if missing.
local ok, noctalia = pcall(require, "noctalia")
if ok and type(noctalia) == "table" and noctalia.apply_theme then
    noctalia.apply_theme()
end
require("workspaces")
require("rule")
require("bind")
require("autostart")
pcall(require, "nixos")
