# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x101416ff
bordercolor = 0x899298ff
focuscolor = 0x83d1f4ff
maximizescreencolor = 0xaecbdaff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe5b6f9ff
globalcolor = 0x004d64ff
overlaycolor = 0x2f4a57ff
